package convert

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Supported HuggingFace architecture names and their GGUF mapping.
var archMapping = map[string]string{
	"LlamaForCausalLM":      "llama",
	"MistralForCausalLM":    "llama",
	"Qwen2ForCausalLM":      "qwen2",
	"Qwen3ForCausalLM":      "qwen3",
	"Qwen2MoeForCausalLM":   "qwen2moe",
	"GemmaForCausalLM":      "gemma",
	"Gemma2ForCausalLM":     "gemma2",
	"Phi3ForCausalLM":       "phi3",
	"InternLM2ForCausalLM":  "internlm2",
	"DeepseekV2ForCausalLM": "deepseek2",
	"BaichuanForCausalLM":   "baichuan",
}

// modelConfig holds config.json fields common to transformer models.
type modelConfig struct {
	Architectures         []string `json:"architectures"`
	HiddenSize            int      `json:"hidden_size"`
	IntermediateSize      int      `json:"intermediate_size"`
	MaxPositionEmbeddings int      `json:"max_position_embeddings"`
	NumAttentionHeads     int      `json:"num_attention_heads"`
	NumHiddenLayers       int      `json:"num_hidden_layers"`
	NumKeyValueHeads      int      `json:"num_key_value_heads"`
	RmsNormEps            float64  `json:"rms_norm_eps"`
	RopeTheta             float64  `json:"rope_theta"`
	VocabSize             int      `json:"vocab_size"`
	HeadDim               int      `json:"head_dim"`
	TieWordEmbeddings     bool     `json:"tie_word_embeddings"`
	ModelType             string   `json:"model_type"`
	BosTokenID            *int     `json:"bos_token_id"`
	EosTokenID            *int     `json:"eos_token_id"`
}

func loadModelConfig(modelDir string) (*modelConfig, error) {
	data, err := os.ReadFile(filepath.Join(modelDir, "config.json"))
	if err != nil {
		return nil, fmt.Errorf("reading config.json: %w", err)
	}

	var cfg modelConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config.json: %w", err)
	}

	if len(cfg.Architectures) == 0 {
		return nil, fmt.Errorf("config.json: no architectures specified")
	}

	// Defaults.
	if cfg.NumKeyValueHeads == 0 {
		cfg.NumKeyValueHeads = cfg.NumAttentionHeads
	}
	if cfg.RopeTheta == 0 {
		cfg.RopeTheta = 10000.0
	}
	if cfg.RmsNormEps == 0 {
		cfg.RmsNormEps = 1e-5
	}

	return &cfg, nil
}

// detectGGUFArch returns the GGUF architecture name for the given HuggingFace architecture.
func detectGGUFArch(hfArch string) (string, error) {
	if ggufArch, ok := archMapping[hfArch]; ok {
		return ggufArch, nil
	}
	return "", fmt.Errorf("unsupported architecture: %s", hfArch)
}

// writeModelKV writes architecture-specific metadata to the GGUF writer.
func writeModelKV(w *ggufWriter, cfg *modelConfig, ggufArch string) {
	prefix := ggufArch

	w.addKV("general.architecture", ggufArch)
	w.addKV("general.name", cfg.ModelType)
	w.addKV("general.file_type", uint32(1)) // F16

	w.addKV(prefix+".block_count", uint32(cfg.NumHiddenLayers))
	w.addKV(prefix+".context_length", uint32(cfg.MaxPositionEmbeddings))
	w.addKV(prefix+".embedding_length", uint32(cfg.HiddenSize))
	w.addKV(prefix+".feed_forward_length", uint32(cfg.IntermediateSize))
	w.addKV(prefix+".attention.head_count", uint32(cfg.NumAttentionHeads))
	w.addKV(prefix+".attention.head_count_kv", uint32(cfg.NumKeyValueHeads))
	w.addKV(prefix+".attention.layer_norm_rms_epsilon", float32(cfg.RmsNormEps))
	w.addKV(prefix+".rope.freq_base", float32(cfg.RopeTheta))

	if cfg.HeadDim > 0 {
		w.addKV(prefix+".attention.key_length", uint32(cfg.HeadDim))
		w.addKV(prefix+".attention.value_length", uint32(cfg.HeadDim))
	}
}

// tensorNameReplacer returns a mapping function for HuggingFace → GGUF tensor names.
// This covers Llama, Qwen, Mistral, DeepSeek, and other architectures that follow
// the standard transformer decoder layout.
func tensorNameMapper(ggufArch string) func(string) string {
	replacements := []string{
		"model.embed_tokens", "token_embd",
		"model.layers.", "blk.",
		".self_attn.q_proj", ".attn_q",
		".self_attn.k_proj", ".attn_k",
		".self_attn.v_proj", ".attn_v",
		".self_attn.o_proj", ".attn_output",
		".self_attn.q_norm", ".attn_q_norm",
		".self_attn.k_norm", ".attn_k_norm",
		".mlp.gate_proj", ".ffn_gate",
		".mlp.up_proj", ".ffn_up",
		".mlp.down_proj", ".ffn_down",
		".input_layernorm", ".attn_norm",
		".post_attention_layernorm", ".ffn_norm",
		"model.norm", "output_norm",
		"lm_head", "output",
	}

	switch ggufArch {
	case "phi3":
		replacements = append(replacements,
			".mlp.gate_up_proj", ".ffn_gate_up",
		)
	}

	r := strings.NewReplacer(replacements...)
	return func(hfName string) string {
		return r.Replace(hfName)
	}
}

// shouldIncludeTensor returns true if the tensor should be included in GGUF output.
// Some tensors (like rotary embeddings) are regenerated by llama.cpp.
func shouldIncludeTensor(name string) bool {
	skip := []string{
		"rotary_emb.inv_freq",
		".rotary_emb.inv_freq",
	}
	for _, s := range skip {
		if strings.HasSuffix(name, s) {
			return false
		}
	}
	return true
}

// handleTiedEmbeddings manages the lm_head.weight tensor based on tie_word_embeddings config.
// When tie_word_embeddings is true, llama.cpp reuses token_embd.weight internally,
// so we strip lm_head.weight to avoid a redundant tensor.
// When tie_word_embeddings is false AND lm_head.weight is missing, we duplicate
// from embed_tokens as a fallback.
func handleTiedEmbeddings(sources []tensorSource, cfg *modelConfig) []tensorSource {
	if cfg.TieWordEmbeddings {
		var filtered []tensorSource
		for _, t := range sources {
			if t.name != "lm_head.weight" {
				filtered = append(filtered, t)
			}
		}
		return filtered
	}

	hasLmHead := false
	for _, t := range sources {
		if t.name == "lm_head.weight" {
			hasLmHead = true
			break
		}
	}
	if hasLmHead {
		return sources
	}

	for _, t := range sources {
		if t.name == "model.embed_tokens.weight" {
			tied := tensorSource{
				name:  "lm_head.weight",
				shape: t.shape,
				dtype: t.dtype,
				file:  t.file,
			}
			return append(sources, tied)
		}
	}

	return sources
}
